### ISSUE TITLE
Download buttons are blue gradients in IE9 Edit

### ISSUE THREAD

**Issue by jimweirich** [neo/rubykoans.com#4]
Originally reported by gregmalcolm in the ruby_koans project.  Moved here because it is a web-site issue.

In Internet Explorer 9 the Ruby Koans website the "Download the Koans" and "Koans online" buttons are showing as a blue gradient instead of the usual red buttons. Probably a javascript loading hicup?

Looks fine in FireFox...

![Screenshot](http://i442.photobucket.com/albums/qq150/gregmalcolm/blueness.png)

**Comment by bakis2011** [comment]
Fixed by https://github.com/neo/rubykoans.com/pull/7
